Numpy Arrays

In [1]:
import sys
import numpy as np

In [3]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [4]:
np.array([1.,0.5,2.,7.5])

array([1. , 0.5, 2. , 7.5])

In [25]:
a=np.array([1,2,3,4,5])
b=np.array([1.,0.5,2.,7.5])

In [7]:
a

array([1, 2, 3, 4, 5])

In [8]:
b

array([1. , 0.5, 2. , 7.5])

In [9]:
a[1]

2

In [10]:
a[0:3]

array([1, 2, 3])

In [11]:
a[:-1]

array([1, 2, 3, 4])

In [12]:
a[-1]

5

In [13]:
a.dtype

dtype('int32')

In [14]:
b.dtype

dtype('float64')

In [24]:
np.array([1,2,3,4,5], dtype=np.int16)

array([1, 2, 3, 4, 5], dtype=int16)

In [27]:
a.dtype

dtype('int32')

DIMENSIONS AND SHAPES

In [7]:
#2D Array
C=np.array([
    [1,2,3,4],
    [5,6,7,8]])

In [8]:
#Checking shape
C.shape

(2, 4)

In [9]:
#Checking dimension
C.ndim

2

In [10]:
#Checking Size
C.size

8

In [11]:
#3D Array
D=np.array([
[
    [6,7,8],
    [9,10,11],
],
[
    [12,13,14],
    [15,16,17]
]])

In [12]:
D

array([[[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]]])

In [13]:
D.shape

(2, 2, 3)

In [14]:
D.ndim

3

In [15]:
D.size

12

INDEXING AND SLICING MATRICES

In [18]:
#Square matrix
E=np.array([
#.  0. 1. 2
    [1,2,3],#0
    [4,5,6],#1
    [7,8,9]])#2

In [20]:
E[1]

array([4, 5, 6])

In [24]:
E[0][2]

3

In [26]:
#E[d1,d2,d3,d4....]
E[0,2]

3

In [28]:
#Slicing
E[:]#Slices everything

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
E[:2]#Slices the first 2 rows

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
E[1:2]

array([[4, 5, 6]])

In [33]:
E[:,:]#Slices Everything

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
E[:,2]#Slices the 3rd Coln of the matrix

array([3, 6, 9])

In [37]:
E[:,:2]#Slices first 2 Colns

array([[1, 2],
       [4, 5],
       [7, 8]])

In [39]:
#Assigning new values in an array
E[0] = np.array([5, 4, 3])


In [40]:
E

array([[5, 4, 3],
       [4, 5, 6],
       [7, 8, 9]])

SUMMARY STATISTICS

In [42]:
F=np.array([4,6,8,9])

In [45]:
F.sum()#Sum of the array

27

In [46]:
F.mean()

6.75

In [47]:
F.std()

1.920286436967152

In [48]:
F.var()

3.6875

In [49]:
E

array([[5, 4, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
E.sum()

51

In [51]:
E.mean()

5.666666666666667

In [52]:
E.std()

1.8856180831641267

NUMPY OPERATIONS

In [53]:
#BROADCASTING AND VECTORIZED OPERATIONS

In [54]:
F=np.array([1,2,3,4])

In [55]:
F

array([1, 2, 3, 4])

In [56]:
F+10

array([11, 12, 13, 14])

In [57]:
F*3

array([ 3,  6,  9, 12])

In [58]:
G=np.arange(4)

In [59]:
G

array([0, 1, 2, 3])

In [60]:
F+G

array([1, 3, 5, 7])

In [61]:
F*G

array([ 0,  2,  6, 12])

In [62]:
#BOOLEAN ARRAYS

In [63]:
H=np.arange(6)

In [64]:
H

array([0, 1, 2, 3, 4, 5])

In [65]:
H[[True,True,False,False,True,False]]

array([0, 1, 4])

In [66]:
H>=3

array([False, False, False,  True,  True,  True])

In [68]:
H[H>=3]

array([3, 4, 5])

In [69]:
H.mean()

2.5

In [70]:
H[H > H.mean()]

array([3, 4, 5])

In [71]:
H[~(H > H.mean())]

array([0, 1, 2])

In [72]:
H[(H == 0) | (H == 1)]

array([0, 1])

In [75]:
I = np.random.randint(50, size=(3, 3))

In [76]:
I

array([[ 0, 17, 28],
       [46, 43, 26],
       [26, 18, 24]])

In [77]:
I[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([ 0, 28, 43, 26, 24])

In [78]:
I > 30

array([[False, False, False],
       [ True,  True, False],
       [False, False, False]])

In [79]:
I[I > 30]

array([46, 43])

In [80]:
#ALGEBRA AND SIZE

In [2]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [3]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [5]:
A.dot(B) #Adds the matrice

array([[20, 14],
       [56, 41],
       [92, 68]])

In [6]:
A @ B #Does the same task as the .dot function.

array([[20, 14],
       [56, 41],
       [92, 68]])

In [8]:
B.T #In NumPy, the .T attribute is used to compute the transpose of an array. Transposing an array means switching its rows and columns.

array([[6, 4, 2],
       [5, 3, 1]])

In [9]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

Useful Numpy functions